### ISSUE TITLE
Add PSR Code Style

### ISSUE THREAD

**Issue by vinyvicente** [williamborba/willer#11]
According: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

**Comment by williamborba** [comment]
Estamos cientes de todos os padrões recomendados pela PSR

**Comment by vinyvicente** [comment]
Ok, só queria contribuir.

**Comment by williamborba** [comment]
de certa forma contribui sim, eu sei q existe os PSR e me esforço pra deixar os códigos conforme o recomendado.

**Comment by vinyvicente** [comment]
tudo bem, mas talvez eu possa contribuir em cima do seu framework codando mesmo, usando TDD, BDD, padronizando código.

**Comment by williamborba** [comment]
amigo @vinyvicente sinta-se a vontade, estou a disposição para tirar todas as dúvidas, pode criar seu branch ou fork caso sinta-se interessado
