### ISSUE TITLE
Remove namespace usages wrong way

### ISSUE THREAD

**Issue by vinyvicente** [williamborba/willer#12]
Needs Refactor all code with namespace usage according: http://php.net/manual/pt_BR/language.namespaces.php

**Comment by williamborba** [comment]
os namespaces estão presentes no framework

**Comment by vinyvicente** [comment]
Estão de maneira equivocada né? não precisa colocar dentro de chaves.

São só padronizações @williamborba , nenhuma crítica, se quiser ajuda ajudo, mas tudo bem, abraços.

**Comment by williamborba** [comment]
com brackets é possível criar mais de um namespace no mesmo arquivo, não q eu fosse usar, e não uso, e recebi sua crítica como construtiva, so usei uma linguagem mas direta na resposta.
